"""Add email and organisation to User model

Revision ID: 05b932daa18c
Revises: e8c1dc5381e1
Create Date: 2023-08-19 19:53:37.108770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b932daa18c'
down_revision = 'e8c1dc5381e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('organisation', sa.String(length=120), nullable=True))
    op.add_column('user_accounts', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user_accounts', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_column('user_accounts', 'email')
    op.drop_column('user_accounts', 'organisation')
    # ### end Alembic commands ###
