"""Add new column updated and language for users

Revision ID: 3383891b5c33
Revises: 4ab2f987ddc2
Create Date: 2023-10-25 06:17:47.646624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3383891b5c33'
down_revision = '4ab2f987ddc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_accounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_accounts', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('user_accounts', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('user_accounts', sa.Column('sub_category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'sub_category')
    op.drop_column('user_accounts', 'category')
    op.drop_column('user_accounts', 'language')
    op.drop_column('user_accounts', 'updated_at')
    op.drop_column('answers', 'updated_at')
    # ### end Alembic commands ###
