"""Add new column subtopic

Revision ID: 4ab2f987ddc2
Revises: 753f2e33ae6e
Create Date: 2023-10-24 16:22:17.863544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab2f987ddc2'
down_revision = '753f2e33ae6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('sub_topic', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('filename', sa.String(), nullable=True))
    op.alter_column('questions', 'sentence',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'sentence',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('questions', 'filename')
    op.drop_column('questions', 'sub_topic')
    # ### end Alembic commands ###
