"""Add new columns

Revision ID: 4f2b1efa0aaf
Revises: 78d3ebef3142
Create Date: 2023-09-19 21:22:01.212949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2b1efa0aaf'
down_revision = '78d3ebef3142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('fluency', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('relevance', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('coherence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'coherence')
    op.drop_column('answers', 'relevance')
    op.drop_column('answers', 'fluency')
    # ### end Alembic commands ###
