"""empty message

Revision ID: 54011935ea10
Revises: fea3ec9fdf73
Create Date: 2023-07-26 16:37:57.262132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54011935ea10'
down_revision = 'fea3ec9fdf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
