"""Add new context ranked by column

Revision ID: 753f2e33ae6e
Revises: 83815e6401e5
Create Date: 2023-10-19 12:05:22.361414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753f2e33ae6e'
down_revision = '83815e6401e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'context')
    # ### end Alembic commands ###
