"""Add a category, location and animal crop to question model

Revision ID: 78d3ebef3142
Revises: fdbb498aaf46
Create Date: 2023-09-02 18:44:06.936835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d3ebef3142'
down_revision = 'fdbb498aaf46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('animal_crop', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('location', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'location')
    op.drop_column('questions', 'animal_crop')
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###
