"""empty message

Revision ID: 88f04beb48b1
Revises: 
Create Date: 2024-03-23 18:52:45.973413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f04beb48b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schoolclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('house', sa.String(length=80), nullable=True),
    sa.Column('registration', sa.String(length=80), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('math_marks', sa.Float(), nullable=True),
    sa.Column('english_marks', sa.Float(), nullable=True),
    sa.Column('science_marks', sa.Float(), nullable=True),
    sa.Column('social_studies_marks', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['schoolclass.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam')
    op.drop_table('user_accounts')
    op.drop_table('schoolclass')
    # ### end Alembic commands ###
