"""Add new answered column

Revision ID: 97ab39cd1158
Revises: 60949d7a6054
Create Date: 2023-09-23 20:45:27.523378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ab39cd1158'
down_revision = '60949d7a6054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answered')
    # ### end Alembic commands ###
