"""Add new rank expert by column

Revision ID: e018d0a634ed
Revises: 58ecd8b9b28e
Create Date: 2023-09-30 13:31:47.402376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e018d0a634ed'
down_revision = '58ecd8b9b28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer_expert_one', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('answer_expert_two', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('answer_count', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('ranking_count', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('rank_expert_one', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('rank_expert_two', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'user_accounts', ['answer_expert_one'], ['id'])
    op.create_foreign_key(None, 'questions', 'user_accounts', ['rank_expert_two'], ['id'])
    op.create_foreign_key(None, 'questions', 'user_accounts', ['rank_expert_one'], ['id'])
    op.create_foreign_key(None, 'questions', 'user_accounts', ['answer_expert_two'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'rank_expert_two')
    op.drop_column('questions', 'rank_expert_one')
    op.drop_column('questions', 'ranking_count')
    op.drop_column('questions', 'answer_count')
    op.drop_column('questions', 'answer_expert_two')
    op.drop_column('questions', 'answer_expert_one')
    # ### end Alembic commands ###
