"""Add correct field to Question model

Revision ID: e8c1dc5381e1
Revises: 10b19e9b41a9
Create Date: 2023-08-15 18:00:37.692896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c1dc5381e1'
down_revision = '10b19e9b41a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'correct')
    # ### end Alembic commands ###
